<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>专户持仓</description>
   <name>Pane-2</name>
   <tag></tag>
   <elementGuidId>6546f6e7-0fc5-49c8-99bf-a15081fe2002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
