<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>公募持仓</description>
   <name>Pane-1</name>
   <tag></tag>
   <elementGuidId>d61c1e29-4411-4da8-ac2f-9b4e28ec0533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
