<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>我的信息</description>
   <name>MyInFO</name>
   <tag></tag>
   <elementGuidId>f84583e5-8487-45db-beaf-58f3164ef7a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='我的信息']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
