<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>我的信息，姓名</description>
   <name>Name</name>
   <tag></tag>
   <elementGuidId>6899010f-0f19-4914-97c7-e69948cb6dc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[text()='唐鹏']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
