<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>下一步按钮</description>
   <name>NextButton_a</name>
   <tag></tag>
   <elementGuidId>7ba35d02-2bac-4997-aa6f-b7f556e7a66d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='authentication']/div[2]//span[text()='下一步']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
