<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>实名认证，勾选单选框</description>
   <name>point</name>
   <tag></tag>
   <elementGuidId>abbd34bb-d0ec-4233-988c-39e317d5f9a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='el-checkbox__inner']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
