<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>重新上传按钮</description>
   <name>ReUploadButton</name>
   <tag></tag>
   <elementGuidId>e035509e-5c10-4dcf-bd1f-7d2dd1a9a579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='重新上传']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
