<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>图形验证码</description>
   <name>ImageCodeInput</name>
   <tag></tag>
   <elementGuidId>001a9eb4-5ad2-4b0f-8a68-6b5c09fd32a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='diaForm']/form/div[2]//inputs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
