<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>短信验证码</description>
   <name>MessageCodeInput</name>
   <tag></tag>
   <elementGuidId>9bea51f5-b38d-47fb-a2d7-a8b574938188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='diaForm']/form/div[3]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
