<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>修改按钮</description>
   <name>MidifyButton</name>
   <tag></tag>
   <elementGuidId>09de6554-3032-4b72-b5c9-76fd799cfef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[text()='修改']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
