<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>我的信息</description>
   <name>Myinfo</name>
   <tag></tag>
   <elementGuidId>4117252b-afa2-46fa-8a34-052b8ec2ae4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='我的信息']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
