<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>手机号输入</description>
   <name>NumInput</name>
   <tag></tag>
   <elementGuidId>08f3b6c8-24f3-4cb5-95b2-1fd08ee1ec75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='diaForm']/form/div[1]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
