<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>确认按钮</description>
   <name>YesButton</name>
   <tag></tag>
   <elementGuidId>f74cd506-2bbc-4db2-afab-65ca926ed5d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='diaForm']/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
