<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>账单查询</description>
   <name>BillQuery</name>
   <tag></tag>
   <elementGuidId>dd206851-8c58-4c7b-8966-ba0afbd214c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='账单查询']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
