<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>自定义查询点击</description>
   <name>CustomQueryClick</name>
   <tag></tag>
   <elementGuidId>5ad119dd-5f4d-4e20-bd07-c358274c5c83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='自定义查询']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
