<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>对账单姓名值</description>
   <name>Name</name>
   <tag></tag>
   <elementGuidId>dc499fe5-55d7-4798-b5ee-06300062c829</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='recentGainsBottom']//span[text()='唐鹏']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
