<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>查询按钮</description>
   <name>QueryButton</name>
   <tag></tag>
   <elementGuidId>920f73b3-57d2-4a35-b471-b41242596f45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='timeQueryBox']/div[2]//span[text()='查询']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
