<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>开始日期</description>
   <name>StartDate</name>
   <tag></tag>
   <elementGuidId>3849c855-fb8e-4388-b3a7-9cb5ab9ba0d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder=&quot;开始日期&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
