<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>生产我的账户模块</description>
   <name>MyAccount</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d818d88d-d469-4a3b-b939-9d34d76a668b</testSuiteGuid>
   <testCaseLink>
      <guid>1fbab407-c6da-4cac-a63f-9dc045cbd3d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Production/Person/MyAccount/AssetDetails</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7e2059a-244c-4495-8056-476282501927</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34fd7e39-bc94-4bb2-ae79-65a8e2d6d4fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Production/Person/MyAccount/BillQuery/BillQuery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03af3d23-5cff-456e-8bea-49b284913e06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cad23f63-3c77-436f-8f9a-7936be251ca0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Production/Person/MyAccount/BillQuery/Custom Query</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7326a145-3242-4504-ab8e-712098905fa3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b2bbf96-db60-463f-a360-0595b4dd234d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Production/Person/MyAccount/MyAsset</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cb5b654-6bbb-46a7-9a5e-fe2140d823c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64b6ccf9-1116-4d26-a037-e3f7f75c7d06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Production/Person/MyAccount/MyBounsQuery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a48f900-320e-4178-ab90-56e460d81b74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97bd3676-2c33-4390-845e-7889db53a75c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Production/Person/MyAccount/ProfitLossQuery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98d2260f-a053-494f-80f4-7ab6a33576f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e2db876-08a6-48af-bcf4-26d3c767cf80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Production/Person/MyAccount/TradeApplyQuery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e2b9251-548b-46a3-9730-f1d0b7aaaa66</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9732a442-d13e-4b91-93e6-65d20cd10990</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Production/Person/MyAccount/TradeConfirmQuery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85ef6cc0-6c92-4b9e-9377-7f32e75f3af4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ce4be5f-1e07-49ce-aabb-c12b74617eb1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Production/Person/MyAccount/ReUploadCard</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71c2ac96-e1bf-4546-99a4-fec0b0096c36</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
