<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>我的资产</description>
   <name>MyAsset</name>
   <tag></tag>
   <elementGuidId>3bebd8a3-cd80-441a-8475-dad2acfa8763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='我的资产']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
