<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>分红查询</description>
   <name>BounsQuery</name>
   <tag></tag>
   <elementGuidId>34ba4516-9662-471a-8ff9-8cedc4a5783f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='分红查询']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
