<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>公告数据列表</description>
   <name>Date</name>
   <tag></tag>
   <elementGuidId>f4c52468-2abf-4e98-b8c3-97f07567de1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='NoticeContent']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
