<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>专户查询</description>
   <name>NoticeQuery</name>
   <tag></tag>
   <elementGuidId>1a8fac2c-29e3-4c6f-a2b8-deef2dd588ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='专户公告']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
