<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>交易记录</description>
   <name>TradeRecord</name>
   <tag></tag>
   <elementGuidId>160f86f2-e777-4b02-83a4-5d240006a836</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='交易记录']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
