<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>收益值</description>
   <name>Profit</name>
   <tag></tag>
   <elementGuidId>52996e1b-b522-4266-b00a-76d3966a1b85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='listContent']/div/div[1]/div[3]/p/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
