<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>盈亏查询</description>
   <name>ProfitLossQuery</name>
   <tag></tag>
   <elementGuidId>7aebba13-b694-47a9-a7f2-a0347d0c8156</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='盈亏查询']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
