<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>专户理财</description>
   <name>Matters</name>
   <tag></tag>
   <elementGuidId>951e3ddb-0dcc-4dfa-9673-68f2b692bfbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='专户理财']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
