<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>我的账户模块</description>
   <name>MyAccount</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>6c1ba88b-5980-4169-b9ee-11f395dbf5c5</testSuiteGuid>
   <testCaseLink>
      <guid>ac967825-f683-4c91-a5f9-8ffa12c9ebed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test/Mechanism/MyAccount/AssetDetails</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea63396b-c31a-406e-ac4a-f24960c8540c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a92d051a-0012-43ff-9c3e-68dd17464a58</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test/Person/MyAccount/BillQuery/BillQuery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>122acb05-c095-4a61-bfaa-8acd7fa64e32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9c9ec3f-1a35-44df-b054-ef645b7da919</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test/Person/MyAccount/BillQuery/Custom Query</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5208b8e8-ea83-4499-a8cc-3aee6c01629e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d06ff91d-48f4-4ca2-bdbe-95de67a03b4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test/Person/MyAccount/ModifyPhoneNum</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c92a257-2937-47d2-ab82-a3cad89aa154</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feb2af58-762d-4122-943d-96ee42e58da2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38596f4e-521b-4d5d-87f7-e35c41892509</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5be98957-49f1-4ad8-876b-63b1db9660d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bea3a062-8ba7-4afe-bccc-c0266deba799</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7be20c8d-f92c-47a6-bba7-c247cd983d90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test/Person/MyAccount/MyAsset</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a0375a0-c36f-4faf-961c-3a9fd428bcc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce7fe3e5-6637-49e6-b3f4-1bf04b88923d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test/Person/MyAccount/MyBounsQuery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7e3d5c1-a8a7-4954-9f3b-fc2910eaaefc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>340a4d3a-6c57-4ba9-9379-5e924742834c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test/Person/MyAccount/ProfitLossQuery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07198d63-19fa-4340-976a-7d676a688cff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f624c486-594e-45e5-bdaf-cd4d110d9240</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test/Mechanism/Matters/TradeApplyQuery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a428018-611a-4bff-b9bf-023c123086d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df48a5a4-120b-45af-8c0b-69443ff47d32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test/Person/MyAccount/TradeConfirmQuery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23996126-6a08-43d2-8e56-f18eed4ce98f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
