<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>我的分红查询</description>
   <name>MyBounsQuery</name>
   <tag></tag>
   <elementGuidId>220ef6f3-db16-469f-a75c-812dd30091be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='我的分红']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
