<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>查询按钮</description>
   <name>QueryButton</name>
   <tag></tag>
   <elementGuidId>7a142127-e8ff-4627-a62c-2c8f187e9fdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='查询']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
