<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>点击机构登录查询</description>
   <name>ClickMechanismLogin</name>
   <tag></tag>
   <elementGuidId>503d89d3-50f5-4955-9129-ff6920016f05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='机构登录查询']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
