<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>跳过按钮</description>
   <name>passbutton</name>
   <tag></tag>
   <elementGuidId>07ab76ee-f796-46bd-9981-d96e54d33e74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='跳过']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
