<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>交易确认点击</description>
   <name>TradeConfirm</name>
   <tag></tag>
   <elementGuidId>d67f7cb4-0512-4465-a3e3-b2972f5a456c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='交易确认']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
